version: '3.1'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  telemetry-service:
    image: telemetry-mysql:main
    ports:
      - 9001:9001
    restart: always
    environment:
      MYSQL_HOST: MYSQL_HOST
      MYSQL_USER: MYSQL_USER
      MYSQL_PORT: 3306
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_PASSWORD: MYSQL_PASSWORD
      sendAnonymousDataToALL: yes
      UrlForAnonymousDataToALL: http://url
      telemetry_local_storage_type: 'mysql'
      node_env: 'prod'
    depends_on:
      - mysql
volumes:
  db_data:
