version: '3.1'
services:
  telemetry-service:
    image: telemetry-mysql:main
    ports:
      - 9002:9002
    restart: always
    environment:
      MYSQL_HOST:
      MYSQL_USER:
      MYSQL_PORT:
      MYSQL_DATABASE:
      MYSQL_PASSWORD:
      sendAnonymousDataToALL: 'yes'
      UrlForAnonymousDataToALL:
      telemetry_local_storage_type: 'mysql'
      node_env: 'prod'
      telemetry_service_port: 9002
